interface_prj/api/urls.py
from django.urls import path, include
from api.views import LetterViewSet

app_name = 'api'

news_list = LetterViewSet.as_view({'get':'_list'})
news_detail = LetterViewSet.as_view({'get':'retrieve'})

urlpatterns = [
    path('',include('rest_framework.urls', namespace='rest_framework')),
    path('news/',news_list,name='news_list'),
    path('news/<str:sid1>',news_detail, name='news_detail')
]

interface_prj/interface_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls', namespace='news')),
    path('api/', include('api.urls', namespace='api')),
]

interface_prj/news/urls.py
from django.urls import path
from django.conf.urls import url

from news import views

app_name='news'
urlpatterns = [
    path('',views.news_list, name='news_list'),
    path('news/search/', views.news_search, name='news_search'),
    path('news/sports/', views.news_category_sports, name='news_category_sports'),   #추가
    path('news/sports/<str:sports>/', views.news_sports, name='news_sports'),
    path('news/<str:sid1>/', views.news_category_list, name='news_category_list'), #추가
    path('news/<str:sid1>/<str:sid2>/', views.news_detail, name='news_detail'),
]

interface_prj/news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


#class Category(models.Model):

class Letter(models.Model):
    # 큰 주제
    category = models.CharField(max_length=10, default="", null=True)
    # 작은 주제
    topic = models.CharField(max_length=10, default="", null=True)
    # 기사제목
    title = models.CharField(max_length=100,default="", primary_key=True)
    # 기사링크
    letter_link = models.URLField(max_length=100)
    # 날짜
    published_date = models.CharField(max_length=20, default="", null=True)
    # 조회 시간
    created_date = models.DateTimeField(default=timezone.now)
    # 미리보기
    preview = models.TextField()
    # 신문사
    writer = models.CharField(max_length=20,default="", null=True)

    def __str__(self):
        return self.title

interface_prj/news/forms.py
from django import forms

class SearchForm(forms.Form):
    news_topic = forms.CharField(label='Topic keyword',max_length=10)
    news_title = forms.CharField(label='Search keyword', max_length=20)

#update, delete form
class UDForm(forms.Form):
    UD = forms.CharField(label='UD',max_length=10)

interface_prj/news/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from news.models import Letter 

from django.utils import timezone
import time
from news._crawling import parsing, selenium_parsing, new100_parsing, selenium_parsing_new100

from news.forms import SearchForm, UDForm
from django.db.models import Q
from django.views.generic.edit import FormView

# Create your views here.

def news_list(request):
    contents = {}
    key = 0
    try:
        economy=  Letter.objects.filter(category__icontains='101' )#.order_by('-created_date')
        it_sc = Letter.objects.filter(category__icontains='105' )#.order_by('-created_date')
        sports= Letter.objects.filter(category__icontains='sports' )#.order_by('-created_date')
        contents = {'economy': economy , 'it_sc': it_sc, 'sports':sports}
    except:
        key=1
        
    return render(request, 'news/news_list.html',{'message':contents, 'key':key})


def news_category_sports(request):
    key = ['sports',]
    sports=['kbaseball','kfootball','wfootball']
    sportss=[]
    contents={}
    func = lambda __sid1__, __sid2__: Letter.objects.filter(category__icontains=__sid1__, topic__icontains=__sid2__)#.order_by('-created_date')
    for sid2 in sports:
        sportss.append(func('sports',sid2))
        contents = {'m': sportss}
    key.append(sports)
    return render(request, 'news/news_category.html', {'message': contents , 'key': key})


def news_category_list(request, sid1):
    key = [sid1,]
    economy = ['259','258','261']
    it_sc=['731','226','227']
    economys=[]
    it_scs=[]
    contents={}
    func = lambda __sid1__,__sid2__: Letter.objects.filter(category__icontains=__sid1__, topic__icontains=__sid2__)
    if key[0] =='101':
        print('101')
        for sid2 in economy:
            economy_topic= func(sid1,sid2)
            economys.append(economy_topic)
        contents={'m': economys}
        key.append(economy)

    elif key[0] == '105':
        print('105')
        for sid2 in it_sc:
            it_topic = func(sid1,sid2)
            it_scs.append(it_topic)
        contents={'m': it_scs}
        key.append(it_sc)


    return render(request, 'news/news_category.html', {'message': contents , 'key': key})


def news_detail(request, sid1, sid2):
    mylist = [sid1, sid2]
    if request.method == 'POST':
        UDform = UDForm(request.POST)
        if UDform.is_valid():
            # 최신 데이터 10개 가져오기
            if UDform.cleaned_data['UD'] == 'update':
                contents = parsing(sid1, sid2)
                for data in contents:
                    form = Letter(
                        category=sid1,
                        topic=sid2,
                        title= data[0],
                        letter_link=data[1],
                        published_date=data[2],
                        preview= data[3],
                        writer=data[4]
                        )
                    form.save()
            # 최신 데이터 100개 가져오기
            elif UDform.cleaned_data['UD'] == 'new100':
                contents = new100_parsing(sid1,sid2)
                for data in contents:
                    form = Letter(
                        category=sid1,
                        topic=sid2,
                        title= data[0],
                        letter_link=data[1],
                        published_date=data[2],
                        preview= data[3],
                        writer=data[4]
                        )
                    form.save()
            # 데이터 전부 삭제
            elif UDform.cleaned_data['UD'] =='delete':
                Letter.objects.filter(topic=sid2).delete()

    else:
        print('GET')
    News = Letter.objects.filter(topic= sid2)
    
    # pagination
    paginator = Paginator(News,3)
    page_no = request.GET.get('page')
    try:
        News_p = paginator.page(page_no)
    except PageNotAnInteger:
        News_p = paginator.page(1)
    except EmptyPage:
        News_p = paginator.page(paginator.num_pages)

    return render(request, 'news/news_detail.html' ,{'message': News_p, 'key':mylist})


def news_sports(request, sports):
    if request.method == 'POST':       
        
        UDform = UDForm(request.POST)
        if UDform.is_valid():
            if UDform.cleaned_data['UD'] == 'update':
                contents = selenium_parsing(sports)
                for data in contents:
                    form = Letter(
                        category = 'sports',
                        topic= sports,
                        title= data[0],
                        letter_link=data[1],
                        published_date=data[2],
                        preview= data[3],
                        writer=data[4]
                        )
                    form.save()
            elif UDform.cleaned_data['UD'] == 'new100':
                contents = selenium_parsing_new100(sports)
                for data in contents:
                    form = Letter(
                        category = 'sports',
                        topic= sports,
                        title= data[0],
                        letter_link=data[1],
                        published_date=data[2],
                        preview= data[3],
                        writer=data[4]
                        )
                    form.save()

            elif UDform.cleaned_data['UD'] =='delete':
                Letter.objects.filter(topic=sports).delete()
    else:
        print('GET')
    News = Letter.objects.filter(topic= sports ,created_date__lte = timezone.now())
    paginator = Paginator(News,3)
    page_no = request.GET.get('page')
    try:
        News_p = paginator.page(page_no)
    except PageNotAnInteger:
        News_p = paginator.page(1)
    except EmptyPage:
        News_p = paginator.page(paginator.num_pages)
    return render(request, 'news/news_sports.html',{'message':News_p, 'key':sports})


def news_search(request):
    context ={}
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data['news_topic']
            _title = form.cleaned_data['news_title']
            news_list=[]
            if topic== 'default':
                news_list = Letter.objects.filter(title__icontains=_title)
            else:
                news_func = lambda __x__: Letter.objects.filter(Q(topic__icontains=__x__) & Q(title__icontains=_title)).distinct()
                news_list = news_func(topic)
           
            context['form'] = form
            context['search_keyword'] = _title 
            context['result_list']= news_list
            return render(request, 'news/news_search.html', {'search_list': context})

    else:
        form = SearchForm()

    return render(request, 'news/news_search.html', {'search_list': context})

interface_prj/news/templates/news/home.html
<!DOCTYPE html>
<html lang="ko">
<meta charset="UTF-8">
    <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'news/css/news.css' %}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" type="text/css">
        <title>뉴스 몰아보기</title>
    </head>
   <body>
    <div class="page-header">
        <h1><a href="{% url 'news:news_list' %}">Daily News</a></h1>
    </div>

    <div class="left-side-bar">
        <div class="status-ico">
            <span>▶</span>
            <span>▼</span>
        </div>

        <ul>
            <li>
                <a href="{% url 'news:news_category_list' sid1='101' %}"> 경제 </a>
                <ul>
                    <li><a href="{% url 'news:news_detail' sid1='101' sid2='259' %}"> 금융 </a></li>
                    <li><a href="{% url 'news:news_detail' sid1='101' sid2='258' %}"> 증권 </a></li>
                    <li><a href="{% url 'news:news_detail' sid1='101' sid2='261' %}"> 산업/재계 </a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'news:news_category_list' sid1='105' %}"> IT/과학 </a>
                <ul>
                    <li><a href="{% url 'news:news_detail' sid1='105' sid2='731' %}"> 모바일 </a></li>
                    <li><a href="{% url 'news:news_detail' sid1='105' sid2='226' %}"> 인터넷/SNS </a></li>
                    <li><a href="{% url 'news:news_detail' sid1='105' sid2='227' %}"> 통신/뉴미디어 </a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'news:news_category_sports' %}"> 스포츠 </a>
                <ul>
                    <li><a href="{% url 'news:news_sports' sports='kbaseball' %}"> 야구 </a></li>
                    <li><a href="{% url 'news:news_sports' sports='kfootball' %}"> 축구 </a></li>
                    <li><a href="{% url 'news:news_sports' sports='wfootball' %}"> 해외축구 </a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'news:news_search' %}"> 검색 </a>
            </li>
        </ul>
    </div>

    <div class="content">
    {% block content %}

    {% endblock %}
    </div>
</body>

</html>

interface_prj/news/templates/news/news_category.html
{% extends "news/home.html"%}

{% block content %}
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'news/css/news.css' %}{% endblock %}" />
        <h2>◀ 더보기 </h2>
        <div id="left">
            <h4 id="font-bold"> {{key.1.0|__topic}} </h4>
            {% for data in message.m.0|__zip:"3" %}
                 <a href="{{ data.0.letter_link}}" target="_blank">
                    <p id="font-bold">{{ data.0.title}}</p>
                </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}
        </div>
        <div id="middle">
           <h4 id="font-bold"> {{key.1.1|__topic}} </h4>
            {% for data in message.m.1|__zip:"3" %}
                 <a href="{{ data.0.letter_link}}" target="_blank">
                    <p id="font-bold">{{ data.0.title}}</p>
                </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}
        </div>
        <div id="right">
           <h4 id="font-bold"> {{key.1.2|__topic}} </h4>
            {% for data in message.m.2|__zip:"3" %}
                 <a href="{{ data.0.letter_link}}" target="_blank">
                    <p id="font-bold">{{ data.0.title}}</p>
                </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}

        </div>
    {% endblock %}

interface_prj/news/templates/news/news_detail.html
{% extends "news/home.html"%}

{% block content %}
    {% load static %}
    {% load filters %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'news/css/news.css' %}{% endblock %}" />
    <!-- title : data[0] link: data[1] date: data[2] descs: data[3] writer:
    data[4]-->
    <div class = "save">
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" name="UD" value="new100" class="save btn btn-default">최신 데이터 100개 새로 가져오기
                <span class="glyphicon glyphicon-check"></span>
            </button>
            <button type="submit" name="UD" value="update" class="save btn btn-warning">최신 데이터 10개 새로 가져오기
                <span class="glyphicon glyphicon-check"></span>
            </button>
            <button type="submit" name="UD" value="delete"  class="save btn btn-danger">삭제하기
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </form>
    </div>
    <div>
        <h2 id="font-bold">
        {% if key.0 == '101' %}
            {{ key.1|__topic }}
        {% elif key.0 == '105' %}
            {{ key.1|__topic }}
        {% endif %}
        
        </h2>
        <br>
        {% for data in message%}
            <h4>
                <li id="font-bold">
                    <a href="{{data.letter_link}}" target="_blank">{{ data.title }}</a>
                </li>
            </h4>
            <li>{{data.preview}}</li>
            <li> 신문사: {{data.writer}}</li>
            <li> 게시날짜: {{data.published_date}}</li>

            <hr>
        {% endfor %}
    </div>
    <div id="wrap">
        {% include 'news/news_pagination.html' with page=message %}
    </div>
{% endblock %}

interface_prj/news/templates/news/news_list.html
{% extends "news/home.html"%}

{% block content %}
    {% load static %}
    {% load filters %}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'news/css/news.css' %}{% endblock %}" />
        {% if key == 0 %}
        <h2>◀ 더보기 </h2>
        <div id="left">
            <h4 id="font-bold"> 경제 </h4>
            {% for data in message.economy|__zip:"3" %}
                <a href="{{ data.0.letter_link}}">
                    <p>{{ data.0.title}}</p>
                </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}
        </div>
        <div id="middle">
            <h4 id="font-bold"> IT/과학 </h4>
            {% for data in message.it_sc|__zip:"3" %}
                <a href="{{ data.0.letter_link}}">
                    <p>{{ data.0.title}}</p>
                </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}
        </div>
        <div id="right">
            <h4 id="font-bold"> 스포츠 </h4>
            {% for data in message.sports|__zip:"3" %}
                 <a href="{{ data.0.letter_link}}">
                    <p>{{ data.0.title}}</p>
                 </a>
                {{data.0.preview}}
                <hr>
            {% endfor %}
        </div>
        {% elif key == 1 %}
        <h2> ◀ 데이터가 없습니다. 
            <button class="btn btn-warning">새로 가져오기
                <span class="glyphicon glyphicon-check"></span>
            </button>
            버튼을 눌러서 데이터를 가져오세요.
        </h2>
        {% endif %}
    {% endblock %}

interface_prj/news/templates/news/news_pagination.html
<nav>
    <ul class = "pagination" >
        <li class="page-item">

            
            {% if page.has_previous %}
                <a class="page-link" href="?page={{ page.previous_page_number }}"> Previous </a>
            {% endif %}
        </li>
        <li class="page-item">
            <a class="page-link" href=" ">Page {{page.number}} of {{page.paginator.num_pages}}</a>
        </li>
        <li class="page-item">
            {% if page.has_next %}
                <a class="page-link" href="?page={{page.next_page_number}}">Next</a>
            {% endif %}
        </li>
    </ul>
</nav>

interface_prj/news/templates/news/news_search.html
<!-- base.html 페이지 상속-->

{% extends "news/home.html" %}

{% block content %}
    {% load static %} 
    {% load filters %}

    <link rel = "stylesheet" type = "text/css" href = "{% block stylesheet %}{% static 'news/css/news.css' %}{% endblock %}" /> 
    <div id="content">
        <h2>
            News Search Engine
        </h2>
        <form action="{% url 'news:news_search' %}" method="post">
            {% csrf_token %}

            <label for="news_topic">topic:
            </label>
            <select name="news_topic">
                <option value="default" selected="selected">전체</option>
                <option value="259"> 금융 </option>
                <option value="258"> 증권 </option>
                <option value="261"> 산업/재계 </option>
                <option value="731"> 모바일 </option>
                <option value="226"> 인터넷/SNS </option>
                <option value="227"> 통신/뉴미디어 </option>
                <option value="kbaseball"> 야구 </option>
                <option value="kfootball"> 축구 </option>
                <option value="wfootball"> 해외축구 </option>
            </select>
            <label for="news_title">Search title: </label>
            <input
                id="news_title"
                type="text"
                name="news_title"
                value="{{ search_keyword}}">
                <input type="submit" value="OK"></form>
                <br/><br/> 
        {% if search_list %}
                {% for result in search_list.result_list %}
                <h3>
                    <li id= "font-bold">
                    {{ result.topic|__topic }} 
                   
                    </li>
                </h3>
                <h4>
                    <li>
                        <a href="{{result.letter_link}}" target="_blank">{{ result.title }}</a>
                    </li>
                </h4>
                <li>{{result.preview}}</li>
                <li>{{result.writer}}</li>
                <li>{{result.published_date}}</li>
                <hr>
            {% endfor %}
        {% endif %}
                </div>
                {% endblock %}

interface_prj/news/templates/news/news_sports.html
{% extends "news/home.html"%}

{% block content %}
{% load static %}
    {% load filters %}

<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'news/css/news.css' %}{% endblock %}" />

    <!-- title : data[0] link: data[1] date: data[2] descs: data[3] writer:
    data[4]-->
    <div class = "save">
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" name="UD" value="new100" class="save btn btn-default">최신 데이터 100개 새로 가져오기
                <span class="glyphicon glyphicon-check"></span>
            </button>
             <button type="submit" name="UD" value="update" class="save btn btn-warning">최신 데이터 20개 새로 가져오기
                <span class="glyphicon glyphicon-check"></span>
            </button>
            <button type="submit" name="UD" value="delete"  class="save btn btn-danger">삭제하기
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </form>
    </div>
    <div>
        <h2 id = "font-bold">
         {{ key|__topic }}
        </h2>
        <br>
        {% for data in message%}
            <h4>
                <li id ="font-bold">
                    <a href="{{data.letter_link}}" target="_blank">{{ data.title }}</a>
                </li>
            </h4>
            <li>{{data.preview}}</li>
            <li> 신문사: {{data.writer}}</li>
            <li> 게시날짜: {{data.published_date}}</li>

            <hr>
        {% endfor %}

    </div>
    <div id="wrap">
    {% include 'news/news_pagination.html' with page=message %}
    </div>
{% endblock %}